### ISSUE TITLE
Oscilloscope: Trigger CH1 actually works on CH2

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-android#2101] opened 2020-02-03 13:47 UTC
Oscilloscope: Trigger CH1 actually works on CH2.

**Comment by CodeWithSouma** [comment] 2020-10-19 08:17
@mariobehling  sir, please help me how to fix this problem I want to work on this issue.

**Comment by PrajwalG22** [comment] 2021-02-08 16:00
Hey I have just started with open source contribution.
Can you help me working on this issue.

**Comment by suman-somu** [comment] 2021-11-08 15:17
working on this. 
good to me, if assigned.

thank you.

**Comment by MonuGit9** [comment] 2024-01-13 19:08
Claim

**Comment by marcnause** [comment] 2024-08-04 20:15
I close this issue since triggering works as intended after https://github.com/fossasia/pslab-android/pull/2482 has been merged.

**Closed by marcnause** 2024-08-04 20:15 UTC
Labels: Bug, Codeheat
