### ISSUE TITLE
Compass instrument not properly working

### ISSUE THREAD

**Issue by utsavsachdeva** [fossasia/pslab-android#1448] opened 2018-12-03 13:31 UTC
The degree shown by compass does not show correct direction in the x-plane while it alsochanges  in the y-plane. 

The compass instrument should be accurate in the x-plane only. 
https://photos.app.goo.gl/npu6xgrvW9daW3KW7

**Comment by cweitat** [comment] 2018-12-05 18:23
Duplicate of #1274

**Closed by cweitat** 2018-12-05 18:23 UTC
