### ISSUE TITLE
App crashes when trying to record in Accelerometer

### ISSUE THREAD

**Issue by ho-dor** [fossasia/pslab-android#1474] opened 2018-12-13 08:58 UTC
**Actual Behaviour**

The app is crashing when the record button is pressed in Accelerometer

**Expected Behaviour**

The app should not crash when the record button is pressed and it  should record the readings of accelerometer 

**Steps to reproduce it**

Open accelerometer and press record button on top right.

**LogCat for the issue**

Process: io.pslab, PID: 18386
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
        at io.pslab.others.CSVLogger.writeCSVFile(CSVLogger.java:83)
        at io.pslab.activity.AccelerometerActivity.onOptionsItemSelected(AccelerometerActivity.java:144)
        at android.app.Activity.onMenuItemSelected(Activity.java:3527)

**Screenshots of the issue**

![screenshot_20181213-142153_pslab](https://user-images.githubusercontent.com/37077735/49927121-4432a080-fee3-11e8-837d-4c14472e5c12.jpg)

**Would you like to work on the issue?**

Yes.

**Comment by CloudyPadmal** [comment] 2018-12-13 09:42
Duplicate of #1465

**Closed by CloudyPadmal** 2018-12-13 09:42 UTC
