### ISSUE TITLE
HelpAndFeedback Activity

### ISSUE THREAD

**Issue by uemarica** [fossasia/pslab-android#811] opened 2018-04-28 19:38 UTC
**Actual Behaviour**

Shows an blank screen

**Expected Behaviour**

Helping the user and the developer

**Steps to reproduce it**

Replacing it with a chat activity which can make the development and using process easier.

**Would you like to work on the issue?**

Yes

**Comment by CloudyPadmal** [comment] 2018-05-26 18:45
Closing this as the issue is fixed in #882

**Closed by CloudyPadmal** 2018-05-26 18:45 UTC
