### ISSUE TITLE
Accelerometer instrument using built in and I2C connected sensor

### ISSUE THREAD

**Issue by Vikum94** [fossasia/pslab-android#991] opened 2018-06-07 17:04 UTC
**Actual Behaviour**

There is a MPU6050 compatible sensor reader in the Sensors instrument. 

**Expected Behaviour**

A new instrument with a real-time accelerometer data displaying device.   

**Steps to reproduce it**

> None

**LogCat for the issue**

> None

**Screenshots of the issue**

The new device is like,

![screenshot_2018-06-07-22-24-17](https://user-images.githubusercontent.com/17523141/41114530-58a8ae0e-6aa2-11e8-87ed-7856a1e1c34c.png) | 
![screenshot_2018-06-07-22-24-27](https://user-images.githubusercontent.com/17523141/41114631-99270c5a-6aa2-11e8-8ff0-54e8bcf434d4.png)
--- | ---

**Would you like to work on the issue?**

Yes

**Comment by cweitat** [comment] 2020-05-22 14:43
Duplicate of #993

**Closed by cweitat** 2020-05-22 14:43 UTC
Labels: Feature, Instrument: Sensors
