### ISSUE TITLE
App Close when I use Power Source Tool

### ISSUE THREAD

**Issue by alvinindra** [fossasia/pslab-android#1458] opened 2018-12-09 07:08 UTC
**Actual Behaviour**
I get app close when i use this Power Source tool

**Expected Behaviour**
I hope the tool is repaired

**LogCat for the issue**
When i touch/click the power source tool
I Use Xiaomi Redmi 3s and Android Marshmellow

**Screenshots of the issue**
When i click/touch that close
But no display force close app, when i back is same problem
![issue of app pslab](https://user-images.githubusercontent.com/30944414/49694384-ca857480-fbbb-11e8-97dd-787074953aea.jpeg)

**Would you like to work on the issue?**
Sorry i can't, i just share the information of issue/bug :+1:

**Comment by cweitat** [comment] 2018-12-11 01:10
Can you send a crash log?

**Comment by cweitat** [comment] 2018-12-11 01:11
Duplicate of #1461

**Closed by cweitat** 2018-12-11 01:11 UTC
